---

- name: Download proxysql exporter
  get_url:
    url: https://github.com/percona/proxysql_exporter/releases/download/v1.1.0/proxysql_exporter-1.1.0.linux-amd64.tar.gz
    dest: /tmp/proxysql_exporter.tar.gz

- name: Create proxysql exporter installation dir
  file:
    path: /opt/proxysql_exporter
    state: directory

- name: Install proxysql exporter
  unarchive:
    src: /tmp/proxysql_exporter.tar.gz
    dest: /opt/proxysql_exporter
    extra_opts:
      - --strip-components=1
    remote_src: true

- name: Systemd for proxysql exporter
  template:
    src: proxysql-exporter.service.j2
    dest: /etc/systemd/system/proxysql-exporter.service
  notify: proxysql-exporter restart

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Consul config for prometheus
  copy:
    dest: /etc/consul/consul.d/proxysql.json
    content: >
      {"service": {"id": "proxysql-exporter", "tags": ["prometheus-scraper", "proxysql"], "name": "prometheus-node-exporter", "port": 9101, "meta": {"role": "proxysql"}}}
  notify: consul reload

- name: Consul config for prometheus Native Exporter
  copy:
    dest: /etc/consul/consul.d/proxysql-native.json
    content: >
      {"service": {"id": "proxysql-native-exporter", "tags": ["prometheus-scraper", "proxysql-native"], "name": "prometheus-node-exporter", "port": 6070, "meta": {"role": "proxysql-native"}}}
  notify: consul reload
  when: proxysql_version is version('2.1.0', '>=')



