---

- name: proxysql-exporter restart
  systemd:
    name: proxysql-exporter
    state: restarted
    enabled: yes

- name: consul reload
  systemd:
    name: consul
    state: reloaded

- name: filebeat-ng restart
  systemd:
    name: filebeat-ng
    state: restarted
